language: python
python:
- '3.6'
- '3.7'
- '3.8'
install: bash build_tools/travis/install.sh
script: pytest
deploy:
  provider: pypi
  user: __token__
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch: master
  skip_cleanup: true
  skip_existing: true
  password:
    secure: RoK4i/dTPHkbVDHvEW2UhtAcQFz4Y8BTnMIxlLpygXI5zVx4WTKeVDqcv31i+uUuRTF9DM9l+BcX0TLRxfJBpnl08C6T5o8pMGmXEaWjgYDuUuMKhXTP35mKes/fB2CQwLjeg6JponI1fUelupkmKf6vyrBYKV5aMlxenUXPPtjRiLOoZPDJEkOfd56UAZxa6/Tsv/ZkckTbnVAaiLv/X7IJWIEOEXH1OrZLrcgAK9A49Hr4/wREC6B5p85cJVUXujwaoeWc1hIpZWAA7wqIaiMd/0vjEykpqTRPQ4cfJV977uWZQWJ1j3X5m0paE6gfP2tHQ987yLFvk8eA9Ezu6D81GtmBRFX1HrOJuV1aJprLThbqZHNipOl6+Pm05XcaXHHzysHu22JE0+7gfqAxEvHwtAjdc0lauEjdAuyzq/bFYIxg7cEWiz5AAfNGllGMDfZiKAQgaWjZIRqzYvJ12waWHCNkIJi/YvtJhVFU++RDw2rQcOGNlzdT7LJ5mdk11JQi3UBhyA/3IeqsbjcWeECSwiXMsk7+xjk8kqv7Y/BMgzBNa4RQ0ioS3YLvuMsxW1ZDfWFeyr22N+WnHvxIwqMq/Da2kIDu//YjVnPZUDLatg2k7Zmvse3OMtot1wMrSRgvgVPCJOQHd/4E9DBJwYiT7/c80p+g0d9UABTS51U=
